<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Ioxide.Tests</RootNamespace>
    <AssemblyName>Ioxide.Tests.E2E</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Ioxide.Tests.Harness/Ioxide.Tests.Harness.csproj" />
    <ProjectReference Include="../../src/protocols/ioxide.http2/ioxide.http2.csproj" />
    <ProjectReference Include="../../src/protocols/ioxide.nghttp3/ioxide.nghttp3.csproj" />
    <ProjectReference Include="../../src/protocols/ioxide.http3/ioxide.http3.csproj" />
    <ProjectReference Include="../../src/clients/ioxide.timer/ioxide.timer.csproj" />
  </ItemGroup>

</Project>
